name: release
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

permissions:
  id-token: write
  pull-requests: write
  actions: write
  contents: write

jobs:
  stable:
    if: github.event_name == 'push'
    uses: the-guild-org/shared-config/.github/workflows/release-stable.yml@main
    with:
      releaseScript: release
      nodeVersion: 26
      packageManager: pnpm
    secrets:
      githubToken: ${{ secrets.GITHUB_TOKEN }}

  alpha:
    if:
      github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name ==
      github.repository && github.event.pull_request.title != 'Upcoming Release Changes'
    uses: the-guild-org/shared-config/.github/workflows/release-snapshot.yml@main
    with:
      npmTag: alpha
      buildScript: build
      nodeVersion: 26
      packageManager: pnpm
    secrets:
      githubToken: ${{ secrets.GITHUB_TOKEN }}

  rc:
    uses: the-guild-org/shared-config/.github/workflows/release-snapshot.yml@main
    if:
      github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name ==
      github.repository && github.event.pull_request.title == 'Upcoming Release Changes'
    with:
      npmTag: rc
      restoreDeletedChangesets: false
      buildScript: build
      nodeVersion: 26
      packageManager: pnpm
    secrets:
      githubToken: ${{ secrets.GITHUB_TOKEN }}
